### ISSUE TITLE
links Musk stole and tried to frame me for

### ISSUE THREAD

**Issue by SOMEONEFORYOU** [ayayaQ/Android-Calculator#3]
See also
Change your homepage in Safari on Mac
Customize the Safari browser window on Mac
Helpful?YesNo
Apple Footer

Apple

**Comment by SOMEONEFORYOU** [comment]
http://apple.com

**Comment by moritz-t-w** [comment]
bro what

**Comment by moritz-t-w** [comment]
> links Musk stole and tried to frame me for 

This is the only coherent sentence you've said on GitHub and I have no idea what's going on, why all the #sudo su pull requests? What happened
